export const DataProducts = [
  {
    id: 1,
    title: "Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops",
    description: "The latest and best version to date",
    category: "men's clothing",
    price: 109.95,
    desc: "Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday",
    image: "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_t.png",
  },
  {
    id: 2,
    title: "Mens Casual Premium Slim Fit T-Shirts",
    description: "The latest and best version to date",
    category: "men's clothing",
    price: 22.3,
    desc: "Slim-fitting style, contrast raglan long sleeve, three-button henley placket, light weight & soft fabric for breathable and comfortable wearing. And Solid stitched shirts with round neck made for durability and a great fit for casual fashion wear and diehard baseball fans. The Henley style round neckline includes a three-button placket.",
    image:
      "https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_t.png",
  },
  {
    id: 3,
    title: "Mens Cotton Jacket",
    description: "The latest and best version to date",
    category: "men's clothing",
    price: 55.99,
    desc:"great outerwear jackets for Spring/Autumn/Winter, suitable for many occasions, such as working, hiking, camping, mountain/rock climbing, cycling, traveling or other outdoors. Good gift choice for you or your family member. A warm hearted love to Father, husband or son in this thanksgiving or Christmas Day.",
    image: "https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_t.png",
  },
  {
    id: 4,
    title: "Mens Casual Slim Fit",
    description: "The latest and best version to date",
    category: "men's clothing",
    price: 15.99,
    desc:"The color could be slightly different between on the screen and in practice. / Please note that body builds vary by person, therefore, detailed size information should be reviewed below on the product description.",
    image: "https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_t.png",
  },
  {
    id: 5,
    title: "John Hardy Women's Legends Naga Bracelet",
    description: "The latest and best version to date",
    category: "jewelery",
    price: 695.0,
    desc:"From our Legends Collection, the Naga was inspired by the mythical water dragon that protects the ocean's pearl. Wear facing inward to be bestowed with love and abundance, or outward for protection.",
    image: "https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_t.png",
  },
  {
    id: 6,
    title: "Solid Gold Petite Micropave",
    description: "The latest and best version to date",
    category: "jewelery",
    price: 168.0,
    desc:"Satisfaction Guaranteed. Return or exchange any order within 30 days.Designed and sold by Hafeez Center in the United States. Satisfaction Guaranteed. Return or exchange any order within 30 days.",
    image: "https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_t.png",
  },
  {
    id: 7,
    title: "White Gold Plated Princess",
    description: "The latest and best version to date",
    category: "jewelery",
    price: 9.99,
    desc:"Classic Created Wedding Engagement Solitaire Diamond Promise Ring for Her. Gifts to spoil your love more for Engagement, Wedding, Anniversary, Valentine's Day...",
    image: "https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_t.png",
  },
  {
    id: 8,
    title: "Pierced Owl Rose Gold Plated Double",
    description: "The latest and best version to date",
    category: "jewelery",
    price: 10.99,
    desc:"Rose Gold Plated Double Flared Tunnel Plug Earrings. Made of 316L Stainless Steel",
    image: "https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_t.png",
  },
  {
    id: 9,
    title: "WD 2TB External Hard Drive",
    description: "The latest and best version to date",
    category: "electronics",
    price: 64.0,
    desc:"USB 3.0 and USB 2.0 Compatibility Fast data transfers Improve PC Performance High Capacity; Compatibility Formatted NTFS for Windows 10, Windows 8.1, Windows 7; Reformatting may be required for other operating systems; Compatibility may vary depending on user’s hardware configuration and operating system",
    image: "https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_t.png",
  },
  {
    id: 10,
    title: "SanDisk SSD PLUS 1TB",
    description: "The latest and best version to date",
    category: "electronics",
    price: 109.0,
    desc:"Easy upgrade for faster boot up, shutdown, application load and response (As compared to 5400 RPM SATA 2.5” hard drive; Based on published specifications and internal benchmarking tests using PCMark vantage scores) Boosts burst write performance, making it ideal for typical PC workloads The perfect balance of performance and reliability Read/write speeds of up to 535MB/s/450MB/s (Based on internal testing; Performance may vary depending upon drive capacity, host device, OS and application.)",
    image: "https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_t.png",
  },
  {
    id: 11,
    title: "Silicon Power 256GB SSD",
    description: "The latest and best version to date",
    category: "electronics",
    price: 109.0,
    desc:"3D NAND flash are applied to deliver high transfer speeds Remarkable transfer speeds that enable faster bootup and improved overall system performance. The advanced SLC Cache Technology allows performance boost and longer lifespan 7mm slim design suitable for Ultrabooks and Ultra-slim notebooks. Supports TRIM command, Garbage Collection technology, RAID, and ECC (Error Checking & Correction) to provide the optimized performance and enhanced reliability.",
    image: "https://fakestoreapi.com/img/71kWymZ+c+L._AC_SX679_t.png",
  },
  {
    id: 12,
    title: "WD 4TB Gaming Drive",
    description: "The latest and best version to date",
    category: "electronics",
    price: 114.0,
    desc:"Expand your PS4 gaming experience, Play anywhere Fast and easy, setup Sleek design with high capacity, 3-year manufacturer's limited warranty",
    image: "https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_t.png",
  },
  {
    id: 13,
    title: "Acer 21.5 Full HD Monitor",
    description: "The latest and best version to date",
    category: "electronics",
    price: 599.0,
    desc:"Expand your PS4 gaming experience, Play anywhere Fast and easy, setup Sleek design with high capacity, 3-year manufacturer's limited warranty",
    image: "https://fakestoreapi.com/img/81QpkIctqPL._AC_SX679_t.png",
  },
  {
    id: 14,
    title: "Samsung 49-Inch Curved Monitor",
    description: "The latest and best version to date",
    category: "electronics",
    price: 999.99,
    desc:"49 INCH SUPER ULTRAWIDE 32:9 CURVED GAMING MONITOR with dual 27 inch screen side by side QUANTUM DOT (QLED) TECHNOLOGY, HDR support and factory calibration provides stunningly realistic and accurate color and contrast 144HZ HIGH REFRESH RATE and 1ms ultra fast response time work to eliminate motion blur, ghosting, and reduce input lag",
    image: "https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_t.png",
  },
  {
    id: 15,
    title: "Women's 3-in-1 Snowboard Jacket",
    description: "The latest and best version to date",
    category: "women's clothing",
    price: 56.99,
    desc:"Note:The Jackets is US standard size, Please choose size as your usual wear Material: 100% Polyester; Detachable Liner Fabric: Warm Fleece. Detachable Functional Liner: Skin Friendly, Lightweigt and Warm.Stand Collar Liner jacket, keep you warm in cold weather. Zippered Pockets: 2 Zippered Hand Pockets, 2 Zippered Pockets on Chest (enough to keep cards or keys)and 1 Hidden Pocket Inside.Zippered Hand Pockets and Hidden Pocket keep your things secure. Humanized Design: Adjustable and Detachable Hood and Adjustable cuff to prevent the wind and water,for a comfortable fit. 3 in 1 Detachable Design provide more convenience, you can separate the coat and inner as needed, or wear it together. It is suitable for different season and help you adapt to different climates",
    image: "https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_t.png",
  },
  {
    id: 16,
    title: "Women's Faux Leather Moto Jacket",
    description: "The latest and best version to date",
    category: "women's clothing",
    price: 29.95,
    desc:"100% POLYURETHANE(shell) 100% POLYESTER(lining) 75% POLYESTER 25% COTTON (SWEATER), Faux leather material for style and comfort / 2 pockets of front, 2-For-One Hooded denim style faux leather jacket, Button detail on waist / Detail stitching at sides, HAND WASH ONLY / DO NOT BLEACH / LINE DRY / DO NOT IRON",
    image: "https://fakestoreapi.com/img/81XH0e8fefL._AC_UY879_t.png",
  },
  {
    id: 17,
    title: "Rain Jacket Women Windbreaker",
    description: "The latest and best version to date",
    category: "women's clothing",
    price: 39.99,
    desc:"Lightweight perfet for trip or casual wear---Long sleeve with hooded, adjustable drawstring waist design. Button and zipper front closure raincoat, fully stripes Lined and The Raincoat has 2 side pockets are a good size to hold all kinds of things, it covers the hips, and the hood is generous but doesn't overdo it.Attached Cotton Lined Hood with Adjustable Drawstrings give it a real styled look.",
image: "https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2t.png",
  },
  {
    id: 18,
    title: "Women's Short Sleeve Boat Neck",
    description: "The latest and best version to date",
    category: "women's clothing",
    price: 9.85,
    desc:"95% RAYON 5% SPANDEX, Made in USA or Imported, Do Not Bleach, Lightweight fabric with great stretch for comfort, Ribbed on sleeves and neckline / Double stitching on bottom hem",
    image: "https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_t.png",
  },
  {
    id: 19,
    title: "Opna Women's Short Sleeve",
    description: "The latest and best version to date",
    category: "women's clothing",
    price: 7.95,
    desc:"100% Polyester, Machine wash, 100% cationic polyester interlock, Machine Wash & Pre Shrunk for a Great Fit, Lightweight, roomy and highly breathable with moisture wicking fabric which helps to keep moisture away, Soft Lightweight Fabric with comfortable V-neck collar and a slimmer fit, delivers a sleek, more feminine silhouette and Added Comfort",
    image: "https://fakestoreapi.com/img/51eg55uWmdL._AC_UX679_t.png",
  },
  {
    id: 20,
    title: "DANVOUY Womens T Shirt",
    description: "The latest and best version to date",
    category: "women's clothing",
    price: 12.99,
    desc:"95%Cotton,5%Spandex, Features: Casual, Short Sleeve, Letter Print,V-Neck,Fashion Tees, The fabric is soft and has some stretch., Occasion: Casual/Office/Beach/School/Home/Street. Season: Spring,Summer,Autumn,Winter.",
    image: "https://fakestoreapi.com/img/61pHAEJ4NML._AC_UX679_t.png",
  },
];

// import axios from "axios";

// const products = localStorage.getItem("cartItems")?.replace(/"/g, '');

// export const product = axios.create({
//   baseURL: "https://dummyjson.com/",
//   withCredentials: true,
//   headers: {
//     "Content-Type": "application/json",
//     Authorization: `Bearer ${products}`
//   }, 
// });

